import RootStyleRegistry from "Next/src/system/styles/RootStyleRegistry"
import { Boot } from "Next/src/app/Boot"
import { Layout } from "Apps/Components/Layouts"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link
        href="https://webfonts.artsy.net/all-webfonts.css"
        rel="stylesheet"
        type="text/css"
        // @ts-ignore - Next thing
        precedence="default"
      />
      <body>
        <RootStyleRegistry>
          <Boot>
            <Layout>{children}</Layout>
          </Boot>
        </RootStyleRegistry>
      </body>
    </html>
  )
}
